# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sxr_protocol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12sxr_protocol.proto\x12\x0csxr_protocol\"Y\n\x06packet\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x02(\x07\x12\x0e\n\x06sender\x18\x02 \x02(\x07\x12\x0f\n\x07\x63ommand\x18\x03 \x02(\x07\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x0f\n\x07version\x18\x05 \x01(\t')



_PACKET = DESCRIPTOR.message_types_by_name['packet']
packet = _reflection.GeneratedProtocolMessageType('packet', (_message.Message,), {
  'DESCRIPTOR' : _PACKET,
  '__module__' : 'sxr_protocol_pb2'
  # @@protoc_insertion_point(class_scope:sxr_protocol.packet)
  })
_sym_db.RegisterMessage(packet)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PACKET._serialized_start=36
  _PACKET._serialized_end=125
# @@protoc_insertion_point(module_scope)
