# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ADCLogUIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdcStatusWin(object):
    def setupUi(self, AdcStatusWin):
        AdcStatusWin.setObjectName("AdcStatusWin")
        AdcStatusWin.resize(807, 299)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AdcStatusWin.sizePolicy().hasHeightForWidth())
        AdcStatusWin.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(AdcStatusWin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(AdcStatusWin)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.reboot_pushButton = QtWidgets.QPushButton(AdcStatusWin)
        self.reboot_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.reboot_pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../style/icons/icons8-update-left-rotation-48 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.reboot_pushButton.setIcon(icon)
        self.reboot_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.reboot_pushButton.setObjectName("reboot_pushButton")
        self.verticalLayout.addWidget(self.reboot_pushButton)

        self.retranslateUi(AdcStatusWin)
        QtCore.QMetaObject.connectSlotsByName(AdcStatusWin)

    def retranslateUi(self, AdcStatusWin):
        _translate = QtCore.QCoreApplication.translate
        AdcStatusWin.setWindowTitle(_translate("AdcStatusWin", "ADC log"))
        self.reboot_pushButton.setText(_translate("AdcStatusWin", "Reboot"))
