# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GSAUIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GSAWidgetDesign(object):
    def setupUi(self, GSAWidgetDesign):
        GSAWidgetDesign.setObjectName("GSAWidgetDesign")
        GSAWidgetDesign.resize(431, 185)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GSAWidgetDesign.sizePolicy().hasHeightForWidth())
        GSAWidgetDesign.setSizePolicy(sizePolicy)
        GSAWidgetDesign.setMinimumSize(QtCore.QSize(250, 70))
        self.gridLayout = QtWidgets.QGridLayout(GSAWidgetDesign)
        self.gridLayout.setObjectName("gridLayout")
        self.return_pushButton = QtWidgets.QPushButton(GSAWidgetDesign)
        self.return_pushButton.setMinimumSize(QtCore.QSize(190, 44))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.return_pushButton.setFont(font)
        self.return_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.return_pushButton.setObjectName("return_pushButton")
        self.gridLayout.addWidget(self.return_pushButton, 3, 0, 1, 2)
        self.install_pushButton = QtWidgets.QPushButton(GSAWidgetDesign)
        self.install_pushButton.setMinimumSize(QtCore.QSize(190, 44))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.install_pushButton.setFont(font)
        self.install_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.install_pushButton.setDefault(True)
        self.install_pushButton.setObjectName("install_pushButton")
        self.gridLayout.addWidget(self.install_pushButton, 3, 2, 1, 1)
        self.frequency_doubleSpinBox = QtWidgets.QDoubleSpinBox(GSAWidgetDesign)
        self.frequency_doubleSpinBox.setDecimals(1)
        self.frequency_doubleSpinBox.setMaximum(1000.0)
        self.frequency_doubleSpinBox.setObjectName("frequency_doubleSpinBox")
        self.gridLayout.addWidget(self.frequency_doubleSpinBox, 2, 2, 1, 1)
        self.freq_label = QtWidgets.QLabel(GSAWidgetDesign)
        self.freq_label.setObjectName("freq_label")
        self.gridLayout.addWidget(self.freq_label, 2, 0, 1, 2)
        self.edge_doubleSpinBox = QtWidgets.QDoubleSpinBox(GSAWidgetDesign)
        self.edge_doubleSpinBox.setDecimals(1)
        self.edge_doubleSpinBox.setObjectName("edge_doubleSpinBox")
        self.gridLayout.addWidget(self.edge_doubleSpinBox, 1, 2, 1, 1)
        self.edge_label = QtWidgets.QLabel(GSAWidgetDesign)
        self.edge_label.setObjectName("edge_label")
        self.gridLayout.addWidget(self.edge_label, 1, 0, 1, 2)
        self.amp_comboBox = QtWidgets.QComboBox(GSAWidgetDesign)
        self.amp_comboBox.setObjectName("amp_comboBox")
        self.gridLayout.addWidget(self.amp_comboBox, 0, 2, 1, 1)
        self.amplitude_label = QtWidgets.QLabel(GSAWidgetDesign)
        self.amplitude_label.setObjectName("amplitude_label")
        self.gridLayout.addWidget(self.amplitude_label, 0, 0, 1, 2)

        self.retranslateUi(GSAWidgetDesign)
        QtCore.QMetaObject.connectSlotsByName(GSAWidgetDesign)

    def retranslateUi(self, GSAWidgetDesign):
        _translate = QtCore.QCoreApplication.translate
        GSAWidgetDesign.setWindowTitle(_translate("GSAWidgetDesign", "GSA"))
        self.return_pushButton.setText(_translate("GSAWidgetDesign", "Вернуть настройки"))
        self.install_pushButton.setText(_translate("GSAWidgetDesign", "Установить настройки"))
        self.freq_label.setText(_translate("GSAWidgetDesign", "Частота, Hz"))
        self.edge_label.setText(_translate("GSAWidgetDesign", "Фронт, ns"))
        self.amplitude_label.setText(_translate("GSAWidgetDesign", "Амплитуда, mV"))
