# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AmplifierUIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AmplifierWidgetDesign(object):
    def setupUi(self, AmplifierWidgetDesign):
        AmplifierWidgetDesign.setObjectName("AmplifierWidgetDesign")
        AmplifierWidgetDesign.resize(300, 160)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AmplifierWidgetDesign.sizePolicy().hasHeightForWidth())
        AmplifierWidgetDesign.setSizePolicy(sizePolicy)
        self.splitter = QtWidgets.QSplitter(AmplifierWidgetDesign)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 281, 141))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.gainB_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.gainB_doubleSpinBox.setObjectName("gainB_doubleSpinBox")
        self.gridLayout.addWidget(self.gainB_doubleSpinBox, 1, 1, 1, 1)
        self.gainA_label = QtWidgets.QLabel(self.groupBox)
        self.gainA_label.setObjectName("gainA_label")
        self.gridLayout.addWidget(self.gainA_label, 0, 0, 1, 1)
        self.gainB_label = QtWidgets.QLabel(self.groupBox)
        self.gainB_label.setObjectName("gainB_label")
        self.gridLayout.addWidget(self.gainB_label, 1, 0, 1, 1)
        self.gainA_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.gainA_doubleSpinBox.setObjectName("gainA_doubleSpinBox")
        self.gridLayout.addWidget(self.gainA_doubleSpinBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.decay_label = QtWidgets.QLabel(self.groupBox_2)
        self.decay_label.setObjectName("decay_label")
        self.gridLayout_2.addWidget(self.decay_label, 0, 0, 1, 1)
        self.decay_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.decay_doubleSpinBox.setObjectName("decay_doubleSpinBox")
        self.gridLayout_2.addWidget(self.decay_doubleSpinBox, 0, 1, 1, 1)

        self.retranslateUi(AmplifierWidgetDesign)
        QtCore.QMetaObject.connectSlotsByName(AmplifierWidgetDesign)

    def retranslateUi(self, AmplifierWidgetDesign):
        _translate = QtCore.QCoreApplication.translate
        AmplifierWidgetDesign.setWindowTitle(_translate("AmplifierWidgetDesign", "Amplifier"))
        self.groupBox.setTitle(_translate("AmplifierWidgetDesign", "Коэффициент усиления"))
        self.gainA_label.setText(_translate("AmplifierWidgetDesign", "Канал A"))
        self.gainB_label.setText(_translate("AmplifierWidgetDesign", "Канал B"))
        self.groupBox_2.setTitle(_translate("AmplifierWidgetDesign", "Общие параметры"))
        self.decay_label.setText(_translate("AmplifierWidgetDesign", "Время спада импульса"))
