# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GSAUIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GSAWidgetDesign(object):
    def setupUi(self, GSAWidgetDesign):
        GSAWidgetDesign.setObjectName("GSAWidgetDesign")
        GSAWidgetDesign.resize(300, 85)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GSAWidgetDesign.sizePolicy().hasHeightForWidth())
        GSAWidgetDesign.setSizePolicy(sizePolicy)
        GSAWidgetDesign.setMinimumSize(QtCore.QSize(250, 70))
        self.verticalLayout = QtWidgets.QVBoxLayout(GSAWidgetDesign)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(GSAWidgetDesign)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.amplitude_label = QtWidgets.QLabel(self.groupBox)
        self.amplitude_label.setObjectName("amplitude_label")
        self.gridLayout.addWidget(self.amplitude_label, 0, 0, 1, 1)
        self.amplitude_var_label = QtWidgets.QLabel(self.groupBox)
        self.amplitude_var_label.setObjectName("amplitude_var_label")
        self.gridLayout.addWidget(self.amplitude_var_label, 0, 1, 1, 1)
        self.amplitude_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.amplitude_doubleSpinBox.setObjectName("amplitude_doubleSpinBox")
        self.gridLayout.addWidget(self.amplitude_doubleSpinBox, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(GSAWidgetDesign)
        QtCore.QMetaObject.connectSlotsByName(GSAWidgetDesign)

    def retranslateUi(self, GSAWidgetDesign):
        _translate = QtCore.QCoreApplication.translate
        GSAWidgetDesign.setWindowTitle(_translate("GSAWidgetDesign", "GSA"))
        self.groupBox.setTitle(_translate("GSAWidgetDesign", "ГСА"))
        self.amplitude_label.setText(_translate("GSAWidgetDesign", "Амплитуда импульса"))
        self.amplitude_var_label.setText(_translate("GSAWidgetDesign", "from to"))
