# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MiniX2UIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MiniX2WidgetDesign(object):
    def setupUi(self, MiniX2WidgetDesign):
        MiniX2WidgetDesign.setObjectName("MiniX2WidgetDesign")
        MiniX2WidgetDesign.resize(300, 170)
        self.groupBox = QtWidgets.QGroupBox(MiniX2WidgetDesign)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 280, 81))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.voltage_label = QtWidgets.QLabel(self.groupBox)
        self.voltage_label.setObjectName("voltage_label")
        self.gridLayout.addWidget(self.voltage_label, 0, 0, 1, 1)
        self.voltage_var_label = QtWidgets.QLabel(self.groupBox)
        self.voltage_var_label.setObjectName("voltage_var_label")
        self.gridLayout.addWidget(self.voltage_var_label, 0, 1, 1, 1)
        self.voltage_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.voltage_doubleSpinBox.setObjectName("voltage_doubleSpinBox")
        self.gridLayout.addWidget(self.voltage_doubleSpinBox, 0, 2, 1, 1)
        self.current_label = QtWidgets.QLabel(self.groupBox)
        self.current_label.setObjectName("current_label")
        self.gridLayout.addWidget(self.current_label, 1, 0, 1, 1)
        self.current_var_label = QtWidgets.QLabel(self.groupBox)
        self.current_var_label.setObjectName("current_var_label")
        self.gridLayout.addWidget(self.current_var_label, 1, 1, 1, 1)
        self.current_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.current_doubleSpinBox.setObjectName("current_doubleSpinBox")
        self.gridLayout.addWidget(self.current_doubleSpinBox, 1, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(MiniX2WidgetDesign)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 280, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.enable_label = QtWidgets.QLabel(self.groupBox_2)
        self.enable_label.setObjectName("enable_label")
        self.gridLayout_2.addWidget(self.enable_label, 0, 0, 1, 1)
        self.enable_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.enable_pushButton.setObjectName("enable_pushButton")
        self.gridLayout_2.addWidget(self.enable_pushButton, 0, 1, 1, 1)

        self.retranslateUi(MiniX2WidgetDesign)
        QtCore.QMetaObject.connectSlotsByName(MiniX2WidgetDesign)

    def retranslateUi(self, MiniX2WidgetDesign):
        _translate = QtCore.QCoreApplication.translate
        MiniX2WidgetDesign.setWindowTitle(_translate("MiniX2WidgetDesign", "MiniX2"))
        self.groupBox.setTitle(_translate("MiniX2WidgetDesign", "Параметры"))
        self.voltage_label.setText(_translate("MiniX2WidgetDesign", "Напряжение"))
        self.voltage_var_label.setText(_translate("MiniX2WidgetDesign", "from to"))
        self.current_label.setText(_translate("MiniX2WidgetDesign", "Сила тока"))
        self.current_var_label.setText(_translate("MiniX2WidgetDesign", "from to"))
        self.groupBox_2.setTitle(_translate("MiniX2WidgetDesign", "Mini-X2"))
        self.enable_label.setText(_translate("MiniX2WidgetDesign", "Запуск"))
        self.enable_pushButton.setText(_translate("MiniX2WidgetDesign", "Disable"))
