# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlotterUIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Plotter(object):
    def setupUi(self, Plotter):
        Plotter.setObjectName("Plotter")
        Plotter.resize(472, 125)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Plotter.sizePolicy().hasHeightForWidth())
        Plotter.setSizePolicy(sizePolicy)
        Plotter.setMinimumSize(QtCore.QSize(200, 120))
        self.shot_groupBox = QtWidgets.QGroupBox(Plotter)
        self.shot_groupBox.setGeometry(QtCore.QRect(10, 10, 454, 51))
        self.shot_groupBox.setMinimumSize(QtCore.QSize(0, 51))
        self.shot_groupBox.setMaximumSize(QtCore.QSize(16777215, 51))
        self.shot_groupBox.setObjectName("shot_groupBox")
        self.name_label = QtWidgets.QLabel(self.shot_groupBox)
        self.name_label.setGeometry(QtCore.QRect(10, 20, 69, 16))
        self.name_label.setObjectName("name_label")
        self.no_label = QtWidgets.QLabel(self.shot_groupBox)
        self.no_label.setGeometry(QtCore.QRect(50, 20, 48, 16))
        self.no_label.setObjectName("no_label")
        self.axis_groupBox = QtWidgets.QGroupBox(Plotter)
        self.axis_groupBox.setGeometry(QtCore.QRect(10, 60, 454, 51))
        self.axis_groupBox.setMinimumSize(QtCore.QSize(0, 51))
        self.axis_groupBox.setMaximumSize(QtCore.QSize(16777215, 51))
        self.axis_groupBox.setObjectName("axis_groupBox")
        self.x_ax_label = QtWidgets.QLabel(self.axis_groupBox)
        self.x_ax_label.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.x_ax_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.x_ax_label.setObjectName("x_ax_label")
        self.x_ax_comboBox = QtWidgets.QComboBox(self.axis_groupBox)
        self.x_ax_comboBox.setGeometry(QtCore.QRect(50, 20, 65, 20))
        self.x_ax_comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.x_ax_comboBox.setObjectName("x_ax_comboBox")
        self.x_ax_comboBox.addItem("")
        self.x_ax_comboBox.addItem("")

        self.retranslateUi(Plotter)
        QtCore.QMetaObject.connectSlotsByName(Plotter)

    def retranslateUi(self, Plotter):
        _translate = QtCore.QCoreApplication.translate
        Plotter.setWindowTitle(_translate("Plotter", "Plotter"))
        self.shot_groupBox.setTitle(_translate("Plotter", "Measurement info"))
        self.name_label.setText(_translate("Plotter", "Name:"))
        self.no_label.setText(_translate("Plotter", "000000_0"))
        self.axis_groupBox.setTitle(_translate("Plotter", "Axis"))
        self.x_ax_label.setText(_translate("Plotter", "X units"))
        self.x_ax_comboBox.setItemText(0, _translate("Plotter", "samples"))
        self.x_ax_comboBox.setItemText(1, _translate("Plotter", "ms"))
