# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WarningUIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarningWidgetDesign(object):
    def setupUi(self, WarningWidgetDesign):
        WarningWidgetDesign.setObjectName("WarningWidgetDesign")
        WarningWidgetDesign.resize(300, 90)
        WarningWidgetDesign.setToolTipDuration(-1)
        self.verticalLayout = QtWidgets.QVBoxLayout(WarningWidgetDesign)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(WarningWidgetDesign)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(WarningWidgetDesign)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(WarningWidgetDesign)
        self.buttonBox.accepted.connect(WarningWidgetDesign.accept)
        self.buttonBox.rejected.connect(WarningWidgetDesign.reject)
        QtCore.QMetaObject.connectSlotsByName(WarningWidgetDesign)

    def retranslateUi(self, WarningWidget):
        _translate = QtCore.QCoreApplication.translate
        WarningWidget.setWindowTitle(_translate("WarningWidget", "Exit"))
        self.label.setText(_translate("WarningWidget", "Сохранить всё, выключить приборы и выйти?"))
