# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WarningMiniX2UIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarningMiniX2WidgetDesign(object):
    def setupUi(self, WarningMiniX2WidgetDesign):
        WarningMiniX2WidgetDesign.setObjectName("WarningMiniX2WidgetDesign")
        WarningMiniX2WidgetDesign.resize(281, 90)
        WarningMiniX2WidgetDesign.setToolTipDuration(-1)
        self.verticalLayout = QtWidgets.QVBoxLayout(WarningMiniX2WidgetDesign)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(WarningMiniX2WidgetDesign)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(WarningMiniX2WidgetDesign)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(WarningMiniX2WidgetDesign)
        self.buttonBox.accepted.connect(WarningMiniX2WidgetDesign.accept)
        self.buttonBox.rejected.connect(WarningMiniX2WidgetDesign.reject)
        QtCore.QMetaObject.connectSlotsByName(WarningMiniX2WidgetDesign)

    def retranslateUi(self, WarningMiniX2Widget):
        _translate = QtCore.QCoreApplication.translate
        WarningMiniX2Widget.setWindowTitle(_translate("WarningMiniX2Widget", "Warning"))
        self.label.setText(_translate("WarningMiniX2Widget", "Mini-X2 включен!\n"
                                                             "Выключить Mini-X2 и закрыть программу?"))
